# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5b8ee06e-72b4-45e2-9729-568e6eeae9e3";
      fsType = "ext4";
      options = [ "discard" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cb35d252-6959-40b6-8ae5-d1bf2ef5c686"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
